name: Build Globed server

on:
  workflow_dispatch:
  # push:

jobs:
  linux:
    name: Linux (Docker)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          for arch in amd64 arm64; do
            docker buildx build \
              --platform linux/$arch \
              --cache-from type=gha,scope=central-server \
              --cache-to type=gha,mode=max,scope=central-server \
              --output type=local,dest=out-$arch .
          done

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp out-amd64/central-server artifacts/central-server-x64
          cp out-arm64/central-server artifacts/central-server-arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-builds
          path: artifacts/*

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2025-12-01
          target: x86_64-pc-windows-msvc

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          set SERVER_SHARED_PREBUILT_DATA=1
          cargo build --release --features all --target x86_64-pc-windows-msvc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: target/x86_64-pc-windows-msvc/release/central-server.exe

  merge:
    name: Merge artifacts
    runs-on: ubuntu-latest
    needs: [linux, windows]
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: central-server-build
          delete-merged: true
